package io.github.soundremote.util

const val DEFAULT_SERVER_PORT = 15711
const val DEFAULT_CLIENT_PORT = 15712
const val DEFAULT_SERVER_ADDRESS = "192.168.0.100"
const val DEFAULT_AUDIO_COMPRESSION = Net.COMPRESSION_192
const val DEFAULT_IGNORE_AUDIO_FOCUS = false
const val DEFAULT_SERVER_PASSWORD = "testing123"
